import sys
import os


sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from cryptocore.csprng import generate_random_bytes, generate_key, generate_iv


class TestCSPRNG:

    def test_generate_random_bytes_sizes(self):
        for size in [1, 16, 32, 64, 128]:
            data = generate_random_bytes(size)
            assert len(data) == size
            assert isinstance(data, bytes)

    def test_generate_random_bytes_uniqueness(self):
        samples = [generate_random_bytes(16) for _ in range(10)]
        unique_samples = set(samples)
        assert len(unique_samples) == len(samples), "Generated bytes should be unique"

    def test_generate_key(self):
        key = generate_key()
        assert len(key) == 16
        assert isinstance(key, bytes)

    def test_generate_iv(self):
        iv = generate_iv()
        assert len(iv) == 16
        assert isinstance(iv, bytes)

    def test_key_uniqueness(self):
        key_set = set()
        num_keys = 1000

        for i in range(num_keys):
            key = generate_key()
            key_hex = key.hex()

            assert key_hex not in key_set, f"Duplicate key found at iteration {i}: {key_hex}"
            key_set.add(key_hex)

        print(f"Successfully generated {len(key_set)} unique keys.")
        assert len(key_set) == num_keys

    def test_basic_distribution(self):
        num_samples = 100
        total_bits = 0
        total_ones = 0

        for _ in range(num_samples):
            key = generate_key()
            for byte in key:
                total_ones += bin(byte).count('1')
                total_bits += 8

        ones_ratio = total_ones / total_bits
        print(f"Bit distribution: {ones_ratio:.3%} ones")

        assert 0.45 <= ones_ratio <= 0.55, f"Poor bit distribution: {ones_ratio:.3%}"

    def test_error_handling(self):
        try:
            generate_random_bytes(0)
            assert False, "Should have raised ValueError"
        except ValueError:
            pass  # Ожидаемое исключение

        try:
            generate_random_bytes(-1)
            assert False, "Should have raised ValueError"
        except ValueError:
            pass  # Ожидаемое исключение

    def test_nist_test_data_generation(self):
        total_size = 10_000_000
        output_file = 'nist_test_data.bin'

        bytes_written = 0
        with open(output_file, 'wb') as f:
            while bytes_written < total_size:
                chunk_size = min(4096, total_size - bytes_written)
                random_chunk = generate_random_bytes(chunk_size)
                f.write(random_chunk)
                bytes_written += len(random_chunk)


        assert os.path.exists(output_file)
        assert os.path.getsize(output_file) == total_size
        print(f"Generated {bytes_written} bytes for NIST testing in '{output_file}'")


        os.remove(output_file)


def test_key_generation_integration():

    import tempfile
    from cryptocore.file_io import read_file, write_file
    from cryptocore.modes.ctr import CTRCipher

    test_data = b"Hello, CryptoCore! This is a test message for automatic key generation."


    temp_input = None
    temp_encrypted = None
    temp_decrypted = None

    try:

        import uuid
        temp_dir = tempfile.gettempdir()
        temp_input = os.path.join(temp_dir, f"test_input_{uuid.uuid4().hex}.tmp")
        temp_encrypted = os.path.join(temp_dir, f"test_encrypted_{uuid.uuid4().hex}.tmp")
        temp_decrypted = os.path.join(temp_dir, f"test_decrypted_{uuid.uuid4().hex}.tmp")


        write_file(temp_input, test_data)


        generated_key = generate_key()
        iv = generate_iv()
        cipher_enc = CTRCipher(generated_key, iv)
        encrypted_data = cipher_enc.encrypt(test_data)
        write_file(temp_encrypted, iv + encrypted_data)


        file_data = read_file(temp_encrypted)
        file_iv = file_data[:16]
        actual_encrypted = file_data[16:]

        cipher_dec = CTRCipher(generated_key, file_iv)
        decrypted_data = cipher_dec.decrypt(actual_encrypted)
        write_file(temp_decrypted, decrypted_data)


        assert decrypted_data == test_data
        print("Key generation integration test passed!")

    finally:

        for temp_file in [temp_input, temp_encrypted, temp_decrypted]:
            if temp_file and os.path.exists(temp_file):
                try:
                    os.unlink(temp_file)
                except PermissionError:
                    print(f"Could not delete {temp_file}, skipping...")


def test_weak_key_detection():
    from cryptocore.cli import check_weak_key

    weak_key = bytes([0] * 16)
    result1 = check_weak_key(weak_key)
    print(f"All zeros key: {weak_key.hex()} -> {result1}")
    assert result1 == True, f"All zeros key should be weak, got {result1}"

    weak_key_sequential = bytes(range(16))
    result2 = check_weak_key(weak_key_sequential)
    print(f"Sequential key: {weak_key_sequential.hex()} -> {result2}")
    assert result2 == True, f"Sequential key should be weak, got {result2}"

    weak_key_reverse = bytes([255 - i for i in range(16)])
    result3 = check_weak_key(weak_key_reverse)
    print(f"Reverse sequential key: {weak_key_reverse.hex()} -> {result3}")
    assert result3 == True, f"Reverse sequential key should be weak, got {result3}"

    strong_key = generate_key()
    result4 = check_weak_key(strong_key)
    print(f"Random key: {strong_key.hex()} -> {result4}")
    assert result4 == False, f"Random key should not be weak, got {result4}"

    print(" Weak key detection test passed!")


def test_cli_key_optional_encryption():
    from cryptocore.cli import parse_args
    from unittest.mock import patch


    test_args = [
        'encrypt',
        '--algorithm', 'aes',
        '--mode', 'ctr',
        '--encrypt',
        '--input', 'test.txt',
        '--output', 'test.bin'
    ]

    with patch('sys.argv', ['cryptocore'] + test_args):
        args = parse_args()
        assert args.encrypt
        assert args.key is None

    print("CLI key optional for encryption test passed!")


if __name__ == "__main__":
    print("Running CSPRNG tests...")

    test_obj = TestCSPRNG()

    print("1. Testing basic functionality...")
    test_obj.test_generate_random_bytes_sizes()
    test_obj.test_generate_key()
    test_obj.test_generate_iv()

    print("2. Testing uniqueness...")
    test_obj.test_key_uniqueness()

    print("3. Testing distribution...")
    test_obj.test_basic_distribution()

    print("4. Testing error handling...")
    test_obj.test_error_handling()

    print("5. Running integration test...")
    test_obj.test_nist_test_data_generation()

    print("6. Running end-to-end test...")
    test_key_generation_integration()

    print("7. Testing weak key detection...")
    test_weak_key_detection()

    print("8. Testing CLI key optional...")
    test_cli_key_optional_encryption()

    print("\nAll CSPRNG tests passed!")